### PR TITLE
register marks, document python and pytest dependencies, and test the…

### PR DESCRIPTION
**Pull request by brianmaissy**
… full matrix with tox and travis

Solves #54

### CODE REVIEW

**Comment by ftobia** [comment]
Nice. LGTM.

**Comment by brianmaissy** [comment]
Do you want any other changes or can we merge this?

**Comment by ftobia** [comment]
This looks good, we can merge. Sorry it took so long, I finally had some time to get my home dev environment set up again. (I wanted to run things myself before merging)

If you'd like, go ahead and add your name to the AUTHORS file and I'll merge.

**Comment by brianmaissy** [comment]
added my name. as far as I'm concerned we can merge

**Comment by DavidAntliff** [comment]
Will there be a 0.7 release containing this merge?

**Comment by brianmedigate** [comment]
@ftobia looks like this still hasn't been released

**Comment by mrbean-bremen** [comment]
As mentioned in the README, this project is no longer maintained. You can use `pytest-order` instead, which is a fork from `pytest-ordering`. Note thoough that the marker name has changed to `order` there.

**Pull request merged**
